server.port=8080

# URL k?t n?i ??n database trên pgAdmin 4 c?a b?n
spring.datasource.url=jdbc:postgresql://localhost:5432/fire_suppression_db
spring.datasource.username=postgres
spring.datasource.password=110506
spring.datasource.driver-class-name=org.postgresql.Driver

# ??i chi?u c?u trúc Entity Java v?i các b?ng ?ã t?o th? công d??i Postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect